# Generated by Django 5.1.1 on 2024-09-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_user_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="watchlist",
            new_name="watchlists",
        ),
    ]
