# Generated by Django 5.1.1 on 2024-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_rename_date_ending_auctionlisting_date_ended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
