# Generated by Django 5.1.1 on 2024-10-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_description'),
        ('auctions', '0011_auctionlisting_winner_notified'),
    ]

    operations = [
    ]
